name: oc-login Example
on: [push]
  # push:
  # workflow_dispatch:
  # schedule:
#     - cron: '0 0 * * *'  # every day at midnight

jobs:
  login:
    # This is a github actions environment    
    name: OpenShift Login and Test
    runs-on: ubuntu-20.04
    # environment: "dev"

    steps:
      - uses: actions/checkout@v4

      - shell: bash
        env:
          TEST_USER: ${{ secrets.TEST_USER }}
        run: |
          echo "$TEST_USER" # this line, log your TEST_USER
      
      - name: Echo
        run: |
          echo "TEST_USER is: " "$TEST_USER" "or" $TEST_USER
          
          
      - name: Log in and set context
        # In a real workflow, point the 'uses' to a tag.
        # uses: redhat-actions/oc-login@v1
        uses: ./
        
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          # openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          openshift_username: ${{ secrets.TEST_USER }}
          openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
          # certificate_authority_data: ${{ secrets.CA_DATA }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
          insecure_skip_tls_verify: true
          reveal_cluster_name: true
          
      
      - name: Test
        run: |
          oc api-resources
